# -*- coding: utf-8 -*-
"""mohan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VuiBys7S6-sN6vA900SiQakTOXa_oFIb
"""

import matplotlib.pyplot as plt
stress=[0,50,100,150,200]
strain=[0,0.002,0.004,0.006,0.008]
plt.plot(strain,stress,marker='9')
plt.xlabel("strain")
plt.ylabel("stress(Mpa)")
plt.title("stress-strain curve")
plt.show()

def gear_train_velocity_ratio(driver_teeth,driven_teeth):
  return driven_teeth/driver_teeth
driver=20
driven=60
vr=gear_train_velocity_ratio(driver,driven)
print("velocity Ratio:",vr)

def concrete_volume(length,width,thickness):
  return length*width*thickness
print("concrete volume:",concrete-volume(10,5,2),"m^3")

import matplotlib.pyplot as plt
stress=[10,20,30,40,50]
stain=[0.1,0.2,0.3,0.4,0.5]
plt.plot(strain,stress,marker='10')
plt.xlabel("strain")
plt.ylabel("stress(mpa)")
plt.title("stress-strain curve")
plt.show()

