# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GjCUdZ-BPkaH46ffbfYdlarrDpy0O1BS
"""

def concrete_voiume(length,width,thickness):
  return length*width*thickness
print("concrete_voiume:",concrete_voiume(10,5,0.2),"m^3")

def hazen_williams(Q,C,D):
  return(0.849*(D**2.63)*(Q**0.54))
flow=hazen_williams(0.05,150,0.3)
print("Head Loss(approx):",flow)

import math
def rlc_impedance(R,L,C,F):
  xl=2*math.pi*f*L
  xc=1/(2*math.pi*f*c)
  return math.sqrt(R**2+(xl-xc)**2)
R=100
L=0.5
c=1e-6
f=50
print("RLC circuit impedance:",rlc_impedence(R,L,C,f),"ohms")

