# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1inxrsA7Elk2kP73_Iwd4VMrPikFQXyzi
"""

def add_numbers(a,b):
  return a+b
result=add_numbers(5,3)
print("sum is:",result)

def check_even_odd(num):
  if num%2==0:
    print(f"{num} is Even")
  else:
    print(f"{num} is Odd")
check_even_odd(7)

def check_even_odd(num):
  if num%2==0:
    print(f"{num} is Even")
  else:
    print(f"{num} is Odd")
check_even_odd(190)

from types import FrameType
fruits=["apple","banana","cherry"]
print("Fruits list:",fruits)

numbers=[1,2,3]
numbers.append(4)
print("updated list:",numbers)

colors=["red","green","blue"]
for color in colors:
  print("color:",color)

person=("john",25,"usa")
print("person tuple:",person)

def ohms_law(voltage=None,current=None,resistance=None):
  if voltage is None:
    return current*resistance
  elif current is None:
    return voltage/resistance
  elif resistance is None:
    return voltage/current
v=ohms_law(current=5,resistance=5)
print("voltage:",v,"v")

force=500
area=0.005
stress=force/area
print("stress:",stress,"pa")

v=250
i=5
p=v*i
print("power:",p,"watts")

resistors=[4,6,10]
total_resistance=sum(resistors)
print("Total Resistance in series:",total_resistance,"ohm")

import math
radius=5
area=math.pi*radius**2
print("Area of circle:",area,"cm^2")



force=50
distance=0.2
torque=force*distance
print("torque:",torque,"N-m")

mass=1000
velocity=20
ke=0.5*mass*velocity**2
print("kinetic energy:",ke,"joules")

def volume_cuboid(length,width,height):
  return length*width*height
length=0.5
width=0.5
height=3
volume=volume_cuboid(length,width,height)
print("concentrate volume:",volume,"m^3")

def celsius_to_fahrenheit(c):
  return(c*9/5)+32
temp_c=25
print("Temperature in Fahrenheit:",celsius_to_fahrenheit(temp_c))

output_power=800
input_power=1000
efficiency=(output_power/input_power)*100
print("Efficiency:",efficiency,"%")

def stress(force,arae):
  return force/area
force=10000
area=0.02
stress_val=stress(force,area)
print("stress:",stress_val,"pa")

import math
A=5
omega=2*math.pi
t=0.5
x=A*math.cos(omega*t)
print("displacement:",x,"m")

def area_rectangle(length,width):
     return length*width
length=10
width=5
area=area-rectangle(length,width)
print("area of rectangle:",area,"m^2")

